### ISSUE TITLE
Problems with acspy installed via pip command

### ISSUE THREAD

**Issue by MuziIsabel** [petebachant/ACSpy#25]
The acspy installed via the pip command is not the latest version in Code. This causes the problem ERROR 132 (unable to establish connection) when using openCommEthernetTCP. The main reason for this is the following difference in the two acspy.py files:
![image](https://github.com/petebachant/ACSpy/assets/28729467/42effc15-ab1c-4a0c-bb84-09158b554e39)
Figure 1
![image](https://github.com/petebachant/ACSpy/assets/28729467/bcf09ce4-342b-47b8-b32b-785689a447bc)
Figure 2
The address in Figure 1 is not encoded "10.0.0.100" to bytes type, which is the main reason for this error.

**Comment by MuziIsabel** [comment]
`#include<stdio.h>
void main{
       printf("Hello World");
} `

**Comment by petebachant** [comment]
Which pip command did you use, and what version of ACS SPiiPlus are you using?

**Comment by MuziIsabel** [comment]
```pip install acspy``` and the version of ACS SPiiPlus is v2.70

**Comment by petebachant** [comment]
Gotcha. Yeah, that's probably because the package on PyPI has not been updated in a bit. A temporary workaround is to install directly from the repo. If you have it cloned, you can run `pip install .` from inside, or you can run `pip install https://github.com/petebachant/ACSpy/archive/refs/heads/master.zip`.

**Comment by petebachant** [comment]
The version on PyPI is now up-to-date, so `pip install acspy` should work.
